# -*- coding: utf-8 -*-
"""age calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRPr7a9nY2Jz0k01x8fHGiznLmzVDlns
"""

def ageCalculator(y, m, d):
    import datetime
    today = datetime.datetime.now().date()
    dob = datetime.date(y, m, d)
    age = int((today-dob).days / 365.25)
    print(age)
ageCalculator(2001, 9, 9)

