# -*- coding: utf-8 -*-
"""emojiess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1184s_gGURUvx-tyrIDu5oCvbU7M9M8Vf
"""

pip install emoji

import emoji

print(emoji.emojize("I love reading books:books:"))
print(emoji.emojize("Some people have a very sensitive heart:red_heart:, please be kind with them.:hibiscus:"))