# -*- coding: utf-8 -*-
"""Find missing num.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AnUi9rqKurcFAKxgdT7Hm9NHdEpO8oS0
"""

def findMissingNumbers(n):
    numbers = set(n)
    length = len(n)
    output = []
    for i in range(1, n[-1]):
        if i not in numbers:
            output.append(i)
    return output

listOfNumbers = [1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 13, 14, 16]
print(findMissingNumbers(listOfNumbers))