# -*- coding: utf-8 -*-
"""kutty number guess game .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qEGtinG0TpLX_PhFopV9l-_RBq6JVw-V
"""

import random
n = random.randrange(1,10)
guess = int(input("Enter any number: "))
while n!= guess:
    if guess < n:
        print("Too low")
        guess = int(input("Enter number again: "))
    elif guess > n:
        print("Too high!")
        guess = int(input("Enter number again: "))
    else:
      break
print("jeichtaa maaraa!!")