# -*- coding: utf-8 -*-
"""LCM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fm4SyvNEci2q5STmlEa_g_GEEkCFWTd0
"""

def least_common_multiple(a, b):
    if a > b:
        greater = a
    elif b > a:
        greater = b
    while(True):
        if ((greater % a == 0) and (greater % b == 0)):
            lcm = greater
            break
        greater = greater + 1
    return lcm

print(least_common_multiple(10, 12))