# -*- coding: utf-8 -*-
"""Reverse a string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13L7TnO1-VbYWAAjxzOwQhxlkuykKpk4I
"""

def reverse_string(string):
    return string[::-1]

a = "ayahska"
print(reverse_string(a))