# -*- coding: utf-8 -*-
"""Rock Paper Scissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hg9TJXC9XbKodi0A1hCny2uid7b_-Jgu
"""

import random

player1 = input("Select Rock, Paper, or Scissor :").lower()
Akshu = random.choice(["Rock", "Paper", "Scissor"]).lower()
print("Akshu selected: ", Akshu)

if player1 == "rock" and Akshu == "paper":
    print("Akshu Won")
elif player1 == "paper" and Akshu == "scissor":
    print("Akshu Won")
elif player1 == "scissor" and Akshu == "rock":
    print("Akshu Won")
elif player1 == Akshu:
    print("Tie")
else:
    print("Player 1 Won")