# -*- coding: utf-8 -*-
"""To get execution time .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNZ_uELkdlDI6poMehRs4r6qqLkLjZFZ
"""

from time import time
start = time()

# Python program to create acronyms
word = "Akshaya LN"
text = word.split()
a = " "
for i in text:
    a = a+str(i[0]).upper()
print(a)

end = time()
execution_time = end - start
print("Execution Time : ", execution_time)